# Pinterest Monitor Configuration
# Copy this file to config.ini and adjust settings

[monitoring]
# How often to check boards (in minutes)
check_interval = 15

# Maximum number of boards to check at once
max_boards_per_check = 100

[server]
# Server host and port
host = 0.0.0.0
port = 5001
debug = false

[scraping]
# Delay between board checks (in seconds) to be respectful
request_delay = 0.5

# User agent for requests
user_agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
